version: '3.8'
services:

  # Backend контейнер
  backend:
    # Для установки нужных пакетов используем не чистый образ, а инструкции из конкретного файла Dockerfile
    build:
      context: ./app/api
      dockerfile: ./../../docker/backend/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./app/api:/var/www 
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  nginx:
    image: nginx:latest
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./app/api:/var/www 
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend
  db:
    image: mysql:5.7.22
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'appuser'
      MYSQL_PASSWORD: 'appuser'
    volumes:
      - ./data/mysql:/var/lib/mysql 
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]

  node:
    build:
        context: ./app/api
        dockerfile: ../../docker/nodejs/Dockerfile
    tty: true
    ports:
        - "5173:5173"
    working_dir: /var/www
    volumes:
        - ./app/api:/var/www
  mailpit:
    image: axllent/mailpit:latest
    container_name: fakeSMTP
    restart: always
    volumes:
      - ./data/mailplit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


volumes:
  dbdata:
    driver: local